# Generated by Django 3.0.8 on 2020-07-31 11:56

from django.db import migrations, models
import karmen.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', karmen.models.IdField(serialize=False)),
                ('name', models.CharField(help_text='Printer will be presented by this name.', max_length=255, verbose_name='Name')),
                ('file', models.FileField(upload_to='')),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
