notifications:
  email: false
matrix:
  include:
    - language: python
      python: "3.6"
      install:
        - pip install pipenv
      before_script:
        - cd src/karmen_backend
      script:
        - pipenv install
        - make test
    - language: python
      python: "3.7"
      install:
        - pip install pipenv
      before_script:
        - cd src/karmen_backend
      script:
        - pipenv install
        - make coverage
        - make coveralls
    - language: python
      python: "3.8-dev"
      install:
        - pip install pipenv
      before_script:
        - cd src/karmen_backend
      script:
        - pipenv install
        - make test
    - language: node_js
      node_js: 10
      cache:
        directories:
        - node_modules
        - "$HOME/.npm"
      before_script:
        - cd src/karmen_frontend
        - npm ci
      script:
        - npm run lint
        - npm run build
