notifications:
  email: false
sudo: true
dist: xenial
services:
- docker
addons:
  apt:
    packages:
    - docker-ce
    - jq
matrix:
  allow_failures:
  - python: 3.8-dev
  include:
  - stage: test
    language: python
    python: '3.6'
    install:
    - pip install pipenv
    before_script:
    - cd src/karmen_backend
    script:
    - pipenv install --dev
    - make test
  - language: python
    python: '3.7'
    install:
    - pip install pipenv
    before_script:
    - cd src/karmen_backend
    script:
    - pipenv install --dev
    - make coverage
    - make coveralls
  - language: python
    python: 3.8-dev
    install:
    - pip install pipenv
    before_script:
    - cd src/karmen_backend
    script:
    - pipenv install --dev
    - make test
  - language: node_js
    name: frontend unit tests and build
    node_js: 10
    cache:
      directories:
      - node_modules
      - "$HOME/.npm"
    before_script:
    - cd src/karmen_frontend
    - npm ci
    script:
    - npm run lint
    - npm run test
    - npm run build
  - language: node_js
    name: frontend cypress tests
    stage: test
    node_js: 10
    cache:
      directories:
      - node_modules
      - "$HOME/.npm"
    before_script:
    - cd src/karmen_frontend && npm ci
    script:
    - KARMEN_CLOUD_MODE=0 docker-compose up --build -d
    - while ! curl -I localhost:4000 > /dev/null 2>&1; do echo 'Waiting for server...'; sleep 1; done
    - npm run test:cypress
  - stage: build docker
    if: tag IS present
    language: generic
    before_install:
    - sudo docker run --privileged linuxkit/binfmt:v0.6
    - sudo docker run -d --privileged -p 1234:1234 --name buildkit moby/buildkit:latest
      --addr tcp://0.0.0.0:1234 --oci-worker-platform linux/amd64 --oci-worker-platform
      linux/armhf
    - sudo docker cp buildkit:/usr/bin/buildctl /usr/bin/
    - export BUILDKIT_HOST=tcp://0.0.0.0:1234
    install: true
    script:
    - travis_wait 30 bash .travis/build-images-backend.sh
  - if: tag IS present
    language: generic
    before_install:
    - sudo docker run --privileged linuxkit/binfmt:v0.6
    - sudo docker run -d --privileged -p 1234:1234 --name buildkit moby/buildkit:latest
      --addr tcp://0.0.0.0:1234 --oci-worker-platform linux/amd64 --oci-worker-platform
      linux/armhf
    - sudo docker cp buildkit:/usr/bin/buildctl /usr/bin/
    - export BUILDKIT_HOST=tcp://0.0.0.0:1234
    install: true
    script:
    - bash .travis/build-images-frontend.sh
  - if: tag IS present
    language: generic
    before_install:
    - sudo docker run --privileged linuxkit/binfmt:v0.6
    - sudo docker run -d --privileged -p 1234:1234 --name buildkit moby/buildkit:latest
      --addr tcp://0.0.0.0:1234 --oci-worker-platform linux/amd64 --oci-worker-platform
      linux/armhf
    - sudo docker cp buildkit:/usr/bin/buildctl /usr/bin/
    - export BUILDKIT_HOST=tcp://0.0.0.0:1234
    install: true
    script:
    - bash .travis/build-images-proxy.sh
  - stage: github release
    if: tag IS present
    language: generic
    install: true
    script:
    - bash .travis/make-github-release.sh
    deploy:
      provider: releases
      api_key:
        secure: gFA34DqXsUi4Z3XMVjDPf3lG2A5+qo9b7mAMpIbdaQUhZmvM2V+8XYFw/tl372/emJVqopWTkkHY9cvsUuhNmvwVCQ4A6d9UDL3SxxNnUHmowGuRKJhX1tO6HNdzWSJRsCnlFbzqg/EwVoBRm3np8gyJG8Cvbw5kpMpDxCsfJMZUGdEM38RqCHqY1uMzDbqjgRI5RYEE4Pyt03p2ZHNgUsF3JJkx0GT3tni5bgKAK65p+A/Cy+TolBmMrVFcyTdTdDyOE5FYN9OFRS8iZADvrLJXukUwq5xgZbaY0aRJVtojA6cT1CdT6gSN1pLenQWAXxF4CE8lD6URgoGpaK/QKIyFXIy7QQDlH2ZoKwH2IHmuy/UtcFEad4mVuOF8/j/DjFDuW+OPO+EJ03hl4Bfy5F1gipiLvigtHoj7O7uoKqAqOjEj3lhnZNy9YNOxhbRcb1jfGPihho3h67N5leNjri8inTU6caj/K+5YhUSSYWryUUfqCnsWX7uto01mptiMlCBJpoNt9iG6qoRc9HzagebplNYJ684aYooqIUVcY7wlAW2KB4QjdOtcgd0tZ5VFCsERdD+JRq6KzCBAdWq/dMefGnXUMIqd+FKBkJa1yIaMUMOH4zlIvQ79aU4eiKzNMfh0UMKb+EsvLUC4k5weI8Um6FiRIfOY7HKCRQdOF5k=
      file: ./.travis/release.zip
      skip_cleanup: true
      prerelease: true
      on:
        repo: fragaria/karmen
        tags: true
        condition: '"$TRAVIS_TAG" =~ ^v[0-9.]*-.*$'
  - if: tag IS present
    language: generic
    install: true
    script:
    - bash .travis/make-github-release.sh
    deploy:
      provider: releases
      api_key:
        secure: gFA34DqXsUi4Z3XMVjDPf3lG2A5+qo9b7mAMpIbdaQUhZmvM2V+8XYFw/tl372/emJVqopWTkkHY9cvsUuhNmvwVCQ4A6d9UDL3SxxNnUHmowGuRKJhX1tO6HNdzWSJRsCnlFbzqg/EwVoBRm3np8gyJG8Cvbw5kpMpDxCsfJMZUGdEM38RqCHqY1uMzDbqjgRI5RYEE4Pyt03p2ZHNgUsF3JJkx0GT3tni5bgKAK65p+A/Cy+TolBmMrVFcyTdTdDyOE5FYN9OFRS8iZADvrLJXukUwq5xgZbaY0aRJVtojA6cT1CdT6gSN1pLenQWAXxF4CE8lD6URgoGpaK/QKIyFXIy7QQDlH2ZoKwH2IHmuy/UtcFEad4mVuOF8/j/DjFDuW+OPO+EJ03hl4Bfy5F1gipiLvigtHoj7O7uoKqAqOjEj3lhnZNy9YNOxhbRcb1jfGPihho3h67N5leNjri8inTU6caj/K+5YhUSSYWryUUfqCnsWX7uto01mptiMlCBJpoNt9iG6qoRc9HzagebplNYJ684aYooqIUVcY7wlAW2KB4QjdOtcgd0tZ5VFCsERdD+JRq6KzCBAdWq/dMefGnXUMIqd+FKBkJa1yIaMUMOH4zlIvQ79aU4eiKzNMfh0UMKb+EsvLUC4k5weI8Um6FiRIfOY7HKCRQdOF5k=
      file: ./.travis/release.zip
      skip_cleanup: true
      on:
        repo: fragaria/karmen
        tags: true
        condition: '"$TRAVIS_TAG" =~ ^v[0-9.]*$'
env:
  global:
  - secure: OSoA7AOTIf0Ias9w/TkA+Rw55e/z+Gu1whBSsZp/ncwHmBJom3+uyF/Ry7Hu+7rHwkk29t6pXTvgfGar/BUWZ9FfJAiM+1ixrVaKpxkotJqNfcXDCSCBLznRBy5Odmqv+czMHvYAdLSIPL3p6fcsfy79u4ju1XM2ZluRMXQYycqk0xpe/tIw8KhhhKTZgnuWE57YhoC8m02lcuhkTCUylYsCxhabjghbxgUc4wXq76Tk1EDSjaCM9LMdqP4mUGuj0aYhAvX2v4JTOb55dS+UhlOPlmQ4ZahpopJKFz8HfYQCuaRZGP/L9ap9GLx/Q4BhFvz+7S+CjpJ0dS+i9IdJthufBmrRTcLObBTPF6DiTAXsqxRw2psf1W60+8zHLdzvxYAvAlLmTqR86+yCip83DyGNfnWKBWeJI+Jy309n/tJUxZmsxE4eFjv9oU5i4qRjZVZ7t5eO+evxTSKYuYCf8F7ALv1FA0wG0xq8x77ydrPn+pndSVa+xP3tX/ifqlmSMHr+jMivfqYhqptLTZAwxWKBK2mRc7Xh2TSvlcVNoahNiwOawQQjelOC+1v/5IVh925UVY3PiepuUlSlJc0Cf+Ee/oMxsTyAjd2V2baCgKfrtV28Du36QkLIyrEBU8GNd/KfdnfhBwLHXJEn/SoB8UpD3/BxfnZU6FwAUIYbUAI=
  - secure: e4YXgh+O63zgWYWD12WltX1BSLChLVkRcWh3bmVJjZhALnVZ8z/1ygW5L6/nNiJG+2Iwr09mQhHZWd9jE04RUpvGI08z0uqJb5urTri0+dvYrNAE1mNETJRo6br8GZLbhb68VDrg1HNO/p4/HpGCVQPSZaICFZocnH9PN/Tx87zjabko0Fb5XkQpUhBVVMLHYvET08bgQdkXttrsfNdZSvpUXF+A0I7wQ5TSYMJHklA29aN201ZJa6CWsiom93IOzQ9MpDX6f4v1QcyhB9eir9SnfvDvHyR2O0zhYUrXBtEw3XMO4kbPZ77V/pOpQLk497BHnIG+K5c+Wj2SYnGQ0sTzHsWjQsUPWoS9axn/VYDJFEAI5hnFxfUFSQO4rQFc5+RdWTExkjrkr2PhvPJll1AJfQF45I6NRUBr6kz4F4WJulYCUOAADIVN3xDO1ukMjuAmMIY/DNDMUlVRd1iFvksUkiAMnBR+D3YGKCaLxxvk7/sRDa8CyycoWwglCQ0eaPIwBcDO5vbazyAxiO/pm7gIdQAQRbGus+GKqNzsFGyMtZhodmwu8amdll5hsrLi+YRZ5sSjaLEtlHJprGEkMCw1y/6CV+2OysSOLZMBbIhJyqmlsb+hLjp9xpLrhJl03jDiUvaNGV7isZfUF3jE4eCKRYRHECNQB8k8yjdygOk=
