version: "3.4"
services:
  proxy:
    image: fragaria/karmen-proxy
    network_mode: host
    environment:
      SERVICE_PORT: ${KARMEN_PORT:-80}
      REDIS_HOST: 127.0.0.1
      FRONTEND_HOST: 127.0.0.1
      FRONTEND_PORT: ${KARMEN_FRONTEND_PORT:-9765}
      BACKEND_HOST: 127.0.0.1
      BACKEND_PORT: ${KARMEN_BACKEND_PORT:-9764}
    depends_on:
      - frontend
      - backend_flask
  frontend:
    image: fragaria/karmen-frontend
    network_mode: host
    restart: unless-stopped
    environment:
      ENV: production
      BACKEND_BASE: /api
      SERVICE_PORT: ${KARMEN_FRONTEND_PORT:-9765}
  backend_flask:
    image: fragaria/karmen-backend
    restart: unless-stopped
    network_mode: host # for arp-scan
    environment:
      ENV: production
      SERVICE: flask
      SERVICE_PORT: ${KARMEN_BACKEND_PORT:-9764}
      FLASKR_SETTINGS: "${FLASKR_SETTINGS:-../config.local.cfg}"
    volumes:
      - ./config.local.cfg:/usr/src/app/config.local.cfg
      - ./karmen-files:/tmp/karmen-files
      - /var/run/dbus:/var/run/dbus # for mdns resolution
    privileged: true # for mdns resolution
    depends_on:
      - files
      - redis
      - dbmigrations
  files:
    image: fragaria/karmen-backend
    user: root
    command: bash -c 'chown -R www-data:www-data /tmp/karmen-files && chmod -R g+sw /tmp/karmen-files'
    volumes:
      - ./karmen-files:/tmp/karmen-files
  dbfiles:
    image: fragaria/karmen-backend
    user: root
    command: bash -c 'chown -R 1000:1000 /var/lib/postgresql/data && chmod -R g+sw /var/lib/postgresql/data'
    volumes:
      - ./db/data:/var/lib/postgresql/data
  dbmigrations:
    image: fragaria/karmen-backend
    network_mode: host
    command: scripts/migrate.sh
    environment:
      ENV: production
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5433
    depends_on:
      - postgres
  backend_celery_worker:
    image: fragaria/karmen-backend
    restart: unless-stopped
    network_mode: host # for arp discovery, requires a different config for redis/postgres conection
    environment:
      ENV: production
      SERVICE: celery-worker
      FLASKR_SETTINGS: "${FLASKR_SETTINGS:-../config.local.cfg}"
    volumes:
      - ./config.local.cfg:/usr/src/app/config.local.cfg
      - ./karmen-files:/tmp/karmen-files
      - /var/run/dbus:/var/run/dbus # for mdns resolution
    privileged: true # for mdns resolution
    depends_on:
      - dbmigrations
      - redis
  backend_celery_beat:
    image: fragaria/karmen-backend
    restart: unless-stopped
    network_mode: host
    environment:
      ENV: production
      SERVICE: celery-beat
      FLASKR_SETTINGS: "${FLASKR_SETTINGS:-../config.local.cfg}"
    volumes:
      - ./config.local.cfg:/usr/src/app/config.local.cfg
    privileged: true # for mdns resolution
    depends_on:
      - dbmigrations
      - redis
  redis:
    image: redis:5
    ports:
      - 127.0.0.1:6379:6379
  postgres:
    image: postgres:11
    user: '1000:1000'
    restart: unless-stopped
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: print3d
      POSTGRES_USER: print3d
      POSTGRES_DB: print3d
    depends_on:
      - dbfiles
    ports:
      - 127.0.0.1:5433:5432
  leds:
    image: fragaria/rpi-led-control
    devices:
      - /dev/gpiomem:/dev/gpiomem
    restart: unless-stopped
    environment:
      START_COLOR: red
    ports:
      - 127.0.0.1:8082:5000
