version: "3.4"
services:
  frontend:
    image: fragaria/karmen-frontend
    restart: unless-stopped
    environment:
      ENV: production
      BACKEND_BASE: http://${BASE_HOST}:8080
    ports:
      - 80:8080
  files:
    image: fragaria/karmen-backend
    user: root
    command: bash -c 'chown -R www-data:www-data /tmp/karmen-files && chmod -R g+sw /tmp/karmen-files'
    volumes:
      - ./karmen-files:/tmp/karmen-files
  backend_flask:
    image: fragaria/karmen-backend
    restart: unless-stopped
    network_mode: host
    environment:
      REDIS_HOST: 127.0.0.1
      ENV: production
      SERVICE: flask
      FLASKR_SETTINGS: "${FLASKR_SETTINGS:-../config.local.cfg}"
    ports:
      - 8080:8080
    volumes:
      - ./config.local.cfg:/usr/src/app/config.local.cfg
      - ./karmen-files:/tmp/karmen-files
      - /var/run/dbus:/var/run/dbus # for mdns resolution
    privileged: true # for mdns resolution
    depends_on:
      - files
      - redis
      - postgres
  backend_celery_worker:
    image: fragaria/karmen-backend
    restart: unless-stopped
    network_mode: host # for arp discovery, requires a different config for redis/postgres conection
    environment:
      ENV: production
      SERVICE: celery-worker
      FLASKR_SETTINGS: "${FLASKR_SETTINGS:-../config.local.cfg}"
    volumes:
      - ./config.local.cfg:/usr/src/app/config.local.cfg
      - /var/run/dbus:/var/run/dbus # for mdns resolution
    privileged: true # for mdns resolution
    depends_on:
      - postgres
      - redis
  backend_celery_beat:
    image: fragaria/karmen-backend
    restart: unless-stopped
    network_mode: host
    environment:
      ENV: production
      SERVICE: celery-beat
      FLASKR_SETTINGS: "${FLASKR_SETTINGS:-../config.local.cfg}"
    volumes:
      - ./config.local.cfg:/usr/src/app/config.local.cfg
    privileged: true # for mdns resolution
    depends_on:
      - postgres
      - redis
  redis:
    image: redis:5
    ports:
      - 127.0.0.1:6379:6379
  postgres:
    image: postgres:11
    restart: unless-stopped
    volumes:
      - ./db/data:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_PASSWORD: print3d
      POSTGRES_USER: print3d
      POSTGRES_DB: print3d
    ports:
      - 127.0.0.1:5433:5432
  leds:
    image: fragaria/rpi-led-control
    devices:
      - /dev/gpiomem:/dev/gpiomem
    restart: unless-stopped
    environment:
      START_COLOR: 16711680
    ports:
      - 127.0.0.1:8082:5000
