# Generated by Django 3.0.8 on 2020-07-31 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_auto_20200731_1156'),
        ('printers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useronprinter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='printeringroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.Group'),
        ),
        migrations.AddField(
            model_name='printeringroup',
            name='printer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printers.Printer'),
        ),
        migrations.AddField(
            model_name='printer',
            name='groups',
            field=models.ManyToManyField(related_name='printers', through='printers.PrinterInGroup', to='groups.Group'),
        ),
        migrations.AddField(
            model_name='printer',
            name='users',
            field=models.ManyToManyField(related_name='printers', through='printers.UserOnPrinter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='useronprinter',
            constraint=models.UniqueConstraint(fields=('printer', 'user'), name='Uniq_user_on_printer'),
        ),
        migrations.AddConstraint(
            model_name='printeringroup',
            constraint=models.UniqueConstraint(fields=('printer', 'group'), name='Uniq_printer_in_group'),
        ),
    ]
