# Generated by Django 3.0.8 on 2020-07-31 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='useringroup',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(related_name='printer_groups', through='groups.UserInGroup', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='useringroup',
            constraint=models.UniqueConstraint(fields=('user', 'group'), name='Uniq_user_in_group'),
        ),
    ]
